server:
  port: 8079
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: credit-service
          uri: lb://credit-service
          predicates:
            - Path=/credit/**
        - id: evalCredit-service
          uri: lb://evalCredit-service
          predicates:
            - Path=/evalCredit/**
        - id: simulateCredit-service
          uri: lb://simulateCredit-service
          predicates:
            - Path=/simulateCredit/**
        - id: tracking-service
          uri: lb://tracking-service
          predicates:
            - Path=/tracking/**